// AUTO-GENERATED by scripts/sync-brands.mjs — do not edit by hand.
// Source of truth: brands/*.json. Run `npm run brand:sync` to regenerate.

export interface Brand {
  id: string
  name: string
  /** Default relay root, e.g. "https://frogclaw.example.com". User-editable. */
  defaultBaseUrl: string
  /** Token group passed to /api/token/ensure-group. */
  group: string
  /** Sort order; the lowest-order brand is the default. */
  order: number
  /** Account sign-up page (optional, "" = hidden). */
  registerUrl: string
  /** Wallet / recharge page (optional, "" = hidden). */
  rechargeUrl: string
  /** Suggested models (login still returns the authoritative list). */
  accountDefaultModels: readonly string[]
  /** Per-model blurbs shown on the model picker (optional). */
  accountModelDescriptions: Readonly<Record<string, string>>
}

export const BRANDS: readonly Brand[] = [
  {
    "id": "frogclaw",
    "name": "FrogClaw",
    "defaultBaseUrl": "",
    "group": "default",
    "order": 0,
    "registerUrl": "",
    "rechargeUrl": "",
    "accountDefaultModels": [],
    "accountModelDescriptions": {}
  },
  {
    "id": "sub2api",
    "name": "Sub2API",
    "defaultBaseUrl": "",
    "group": "default",
    "order": 1,
    "registerUrl": "",
    "rechargeUrl": "",
    "accountDefaultModels": [],
    "accountModelDescriptions": {}
  },
] as const

export const DEFAULT_BRAND_ID = "frogclaw"
