// AUTO-GENERATED by scripts/sync-brands.mjs — do not edit by hand.
// Active brand: huanxingtradereview. Run `npm run brand:sync` (BRAND=<id>) to regenerate.

export interface Brand {
  id: string
  name: string
  /** English display name (used where ASCII is required). */
  appNameEn: string
  /** Default relay root, e.g. "https://frogclaw.example.com". User-editable. */
  defaultBaseUrl: string
  /** Token group passed to /api/token/ensure-group. */
  group: string
  /** Sort order (retained from the brand config). */
  order: number
  /** Account sign-up page (optional, "" = hidden). */
  registerUrl: string
  /** Wallet / recharge page (optional, "" = hidden). */
  rechargeUrl: string
  /** Suggested models (login still returns the authoritative list). */
  accountDefaultModels: readonly string[]
  /** Per-model blurbs shown on the model picker (optional). */
  accountModelDescriptions: Readonly<Record<string, string>>
}

export const BRAND: Brand = {
  "id": "huanxingtradereview",
  "name": "寰星复盘助手",
  "appNameEn": "HuanxingReview",
  "defaultBaseUrl": "https://api.huanxing.ai",
  "group": "default",
  "order": 0,
  "registerUrl": "https://api.huanxing.ai/sign-up",
  "rechargeUrl": "https://api.huanxing.ai/wallet",
  "accountDefaultModels": [
    "deepseek-v4-flash",
    "deepseek-v4-pro",
    "gpt-5.5",
    "kimi-k2.6",
    "minimax-m3",
    "mimo-v2.5-pro",
    "glm-5.1"
  ],
  "accountModelDescriptions": {
    "deepseek-v4-flash": "响应快、成本低，适合日常问答、轻量代码修改和批量文本处理。",
    "deepseek-v4-pro": "更强的推理和代码能力，适合复杂开发、长链路分析和高质量写作。",
    "gpt-5.5": "通用能力强，适合综合任务、工具调用、多轮规划和复杂问题拆解。",
    "kimi-k2.6": "长文本阅读和中文理解表现稳定，适合资料分析、总结和知识密集型任务。",
    "minimax-m3": "中文表达自然，适合内容创作、客服对话和多轮中文沟通。",
    "mimo-v2.5-pro": "偏工程和数学推理，适合代码审查、问题定位和结构化分析。",
    "glm-5.1": "中文场景均衡，适合办公写作、问答和常规 Agent 任务。",
    "claude-opus-4-8": "复杂推理、代码架构和长上下文任务表现突出，只支持 Claude Code 中使用。",
    "claude-opus-4-7": "复杂推理、代码架构和长上下文任务表现突出，只支持 Claude Code 中使用。",
    "claude-opus-4-6": "复杂推理、代码架构和长上下文任务表现突出，只支持 Claude Code 中使用。"
  }
} as const

export const DEFAULT_BRAND_ID = "huanxingtradereview"
