#!/usr/bin/env node
// Build-time brand sync. Reads every brands/*.json (the single source of truth
// for the runtime-selectable brand presets) and generates
// src/lib/brands.generated.ts, consumed by src/lib/brands.ts.
//
// Modeled on TradeReview's scripts/sync-brand.mjs, but this app picks a brand
// at RUNTIME (login screen), so the generated module exports ALL brands as a
// list rather than one active brand.
//
// Usage:
//   node scripts/sync-brands.mjs           regenerate the module
//   node scripts/sync-brands.mjs --check    fail (exit 1) if it is stale
import { readFileSync, writeFileSync, readdirSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const brandsDir = resolve(repoRoot, "brands")
const outFile = resolve(repoRoot, "src/lib/brands.generated.ts")
const checkOnly = process.argv.includes("--check")

const STRING_FIELDS = ["id", "name", "defaultBaseUrl", "group", "registerUrl", "rechargeUrl"]

function fail(msg) {
  console.error(`[sync-brands] ${msg}`)
  process.exit(1)
}

function loadBrand(file) {
  let raw
  try {
    raw = JSON.parse(readFileSync(resolve(brandsDir, file), "utf8"))
  } catch (err) {
    fail(`brands/${file} is not valid JSON: ${err.message}`)
  }
  for (const field of STRING_FIELDS) {
    if (typeof raw[field] !== "string") {
      fail(`brands/${file} missing required string field "${field}"`)
    }
  }
  if (!/^[a-z][a-z0-9-]*$/.test(raw.id)) {
    fail(`brands/${file} has invalid id "${raw.id}" (expected lowercase kebab)`)
  }
  if (typeof raw.order !== "number") fail(`brands/${file} missing numeric "order"`)
  if (!Array.isArray(raw.accountDefaultModels)) fail(`brands/${file} "accountDefaultModels" must be an array`)
  if (raw.accountModelDescriptions == null || typeof raw.accountModelDescriptions !== "object") {
    fail(`brands/${file} "accountModelDescriptions" must be an object`)
  }
  return {
    id: raw.id,
    name: raw.name,
    defaultBaseUrl: raw.defaultBaseUrl,
    group: raw.group,
    order: raw.order,
    registerUrl: raw.registerUrl,
    rechargeUrl: raw.rechargeUrl,
    accountDefaultModels: raw.accountDefaultModels,
    accountModelDescriptions: raw.accountModelDescriptions,
  }
}

function render(brands) {
  const sorted = [...brands].sort((a, b) => (a.order - b.order) || a.id.localeCompare(b.id))
  if (sorted.length === 0) fail("no brand configs found in brands/")
  const defaultId = sorted[0].id
  const body = sorted.map((b) => `  ${JSON.stringify(b, null, 2).split("\n").join("\n  ")},`).join("\n")
  return `// AUTO-GENERATED by scripts/sync-brands.mjs — do not edit by hand.
// Source of truth: brands/*.json. Run \`npm run brand:sync\` to regenerate.

export interface Brand {
  id: string
  name: string
  /** Default relay root, e.g. "https://frogclaw.example.com". User-editable. */
  defaultBaseUrl: string
  /** Token group passed to /api/token/ensure-group. */
  group: string
  /** Sort order; the lowest-order brand is the default. */
  order: number
  /** Account sign-up page (optional, "" = hidden). */
  registerUrl: string
  /** Wallet / recharge page (optional, "" = hidden). */
  rechargeUrl: string
  /** Suggested models (login still returns the authoritative list). */
  accountDefaultModels: readonly string[]
  /** Per-model blurbs shown on the model picker (optional). */
  accountModelDescriptions: Readonly<Record<string, string>>
}

export const BRANDS: readonly Brand[] = [
${body}
] as const

export const DEFAULT_BRAND_ID = ${JSON.stringify(defaultId)}
`
}

const files = readdirSync(brandsDir).filter((f) => f.endsWith(".json"))
const brands = files.map(loadBrand)
const next = render(brands)

if (checkOnly) {
  let current = ""
  try {
    current = readFileSync(outFile, "utf8")
  } catch {
    fail(`${outFile} is missing — run \`npm run brand:sync\``)
  }
  if (current !== next) {
    fail("src/lib/brands.generated.ts is stale — run `npm run brand:sync`")
  }
  console.log("[sync-brands] up to date")
} else {
  writeFileSync(outFile, next)
  console.log(`[sync-brands] wrote ${outFile} (${brands.length} brand(s))`)
}
